name: Transform tokens send from figma
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    types: update-tokens
jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mkdir "tokens" directory
        run: "mkdir -p tokens"

      - name: Filter and create JSON from request body
        id: create-json
        run: |
          echo '${{ github.event.client_payload.tokens }}' | jq -r 'to_entries[] | "\(.key) \(.value | @json)"' | while read key value; do
            filename=$(echo $key | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g').tokens.json
            echo "{\"$key\": $value}" > tokens/$filename
          done

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ${{ github.event.client_payload.commitMessage || 'Tokens updated' }}
          title: "Test CSS variables updated"
          body: "CSS variables have been updated via Figma and need to be reviewed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "main"
